<?php require TEMPLATES . '/site/includes/header.phtml';?>

<div class="row">
    <div class="col-12">
        <?php require TEMPLATES . '/site/includes/message.phtml';?>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <h2>Registrar ou Logar</h2>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-6" style="border-right: 1px solid #CCC;">
        <h3>Registrar</h3>
        <form action="<?=HOME;?>/auth/register" method="post">
            <div class="form-group">
                <label>Nome Completo</label>
                <input type="text" class="form-control" name="name">
            </div>
            
            <div class="form-group">
                <label>E-mail</label>
                <input type="text" class="form-control" name="email">
            </div>
            
            <div class="form-group">
                <label>Senha</label>
                <input type="password" class="form-control" name="password">
            </div>

            <button class="btn btn-success">Cadastrar</button>
        </form>
    </div>
    <div class="col-6">
        <h3>Logar</h3>
        <form action="<?=HOME;?>/auth/login" method="post">
            
            <div class="form-group">
                <label>E-mail</label>
                <input type="text" class="form-control" name="email">
            </div>
            
            <div class="form-group">
                <label>Senha</label>
                <input type="password" class="form-control" name="password">
            </div>

            <button class="btn btn-success">Acessar</button>
        </form>
    </div>
    
   
</div>
<?php require TEMPLATES . '/site/includes/footer.phtml';?>